version: '3.9'

networks:
  octo_validator_network:
    name: octo_validator_network
    external: true

services:
  frontend:
    container_name: octo_validator_frontend
    build:
      context: .
      dockerfile: ./ops/docker/node/local/Dockerfile
    volumes:
      - ./:/var/www/node:cached
      - octo_validator_frontend_node_modules:/var/www/node/node_modules:delegated
    ports:
      - ${PUBLIC_APP_PORT}:${PUBLIC_APP_PORT}
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - octo_validator_network

volumes:
  octo_validator_frontend_node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '${PWD}/node_modules'
