services:
  backend:
    container_name: octo_validator_backend
    build:
      context: .
      dockerfile: ./ops/docker/backend/staging/Dockerfile
      args:
        - NODE_ENV=staging
        - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}

    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    container_name: octo_validator_postgres
    build:
      context: ./ops/docker/postgres
      dockerfile: staging/Dockerfile
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
      - PGTZ=${TZ}
    volumes:
      - ./ops/docker/postgres/common/data:/var/lib/postgresql/data:delegated
